# -*- coding: utf-8 -*-
"""pcf261_sem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-66z_NIaUqcPxSxWUzfn1j5Etf44GFT

# Modelos Computacionales: Mapa Logístico y Gráficos con Matplotlib

Notebook de ejemplo para la sesión 01: gráficos, mapa logístico, cobweb, bifurcación, histogramas y exponente de Lyapunov.
"""

# 1. Gráfico de líneas
import numpy as np
import matplotlib.pyplot as plt

def f(t):
    return np.exp(-t/2.0) * np.cos(15.0 * t)

X = np.linspace(2.0, 5.0, 1000)
Y = f(X)

plt.plot(X, Y, 'b-')
plt.xlabel("t")
plt.ylabel("f(t)")
plt.title("Gráfico de línea: f(t) = e^{-t/2} cos(15 t)")
plt.grid(True)
plt.show()

# 2. Gráfico de dispersión (scatter)
import numpy as np
import matplotlib.pyplot as plt

N = 1000
x = np.random.rand(N)
y = np.random.rand(N)

plt.scatter(x, y, s=10, alpha=0.5)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Gráfico de dispersión")
plt.grid(True)
plt.show()

# 3. Mapa logístico: órbita temporal
import numpy as np
import matplotlib.pyplot as plt

mu = 3.2
x0 = 0.2
n_iter = 100

x = np.empty(n_iter)
x[0] = x0

for n in range(1, n_iter):
    x[n] = mu * x[n-1] * (1 - x[n-1])

plt.plot(range(n_iter), x, 'b.-')
plt.xlabel("n")
plt.ylabel("x_n")
plt.title(f"Órbita del mapa logístico (mu = {mu})")
plt.grid(True)
plt.show()

# 4. Cobweb del mapa logístico
import numpy as np
import matplotlib.pyplot as plt

mu = 3.2

def f_logistic(x):
    return mu * x * (1 - x)

x = np.linspace(0, 1, 500)

plt.plot(x, f_logistic(x), 'b', label="f(x)")
plt.plot(x, x, 'k--', label="y = x")

xn = 0.2
n_iter = 50

for i in range(n_iter):
    xnext = f_logistic(xn)
    plt.plot([xn, xn], [xn, xnext], 'r', linewidth=0.8)
    plt.plot([xn, xnext], [xnext, xnext], 'r', linewidth=0.8)
    xn = xnext

plt.xlim(0, 1)
plt.ylim(0, 1)
plt.xlabel("x_n")
plt.ylabel("x_{n+1}")
plt.title(f"Cobweb del mapa logístico (mu = {mu})")
plt.legend()
plt.grid(True)
plt.show()

# 5. Diagrama de bifurcación del mapa logístico
import numpy as np
import matplotlib.pyplot as plt

n_mu = 2000
mu_values = np.linspace(2.5, 4.0, n_mu)

iterations = 1000
last = 100

for mu in mu_values:
    x = 0.5
    for i in range(iterations):
        x = mu * x * (1 - x)
        if i >= iterations - last:
            plt.plot(mu, x, 'k.', markersize=0.5)

plt.xlabel("mu")
plt.ylabel("x")
plt.title("Diagrama de bifurcación del mapa logístico")
plt.show()

# 6. Histograma de iteraciones (distribución de x)
import numpy as np
import matplotlib.pyplot as plt

mu = 3.99
n_iter = 100000
burn_in = 1000

x = np.empty(n_iter)
x[0] = 0.5

for n in range(1, n_iter):
    x[n] = mu * x[n-1] * (1 - x[n-1])

x_ss = x[burn_in:]

plt.hist(x_ss, bins=100, density=True, alpha=0.7, color='steelblue')
plt.xlabel("x")
plt.ylabel("densidad")
plt.title(f"Histograma del mapa logístico (mu = {mu})")
plt.grid(True)
plt.show()

# 7. Exponente de Lyapunov para el mapa logístico
import numpy as np

def logistic_map(x, mu):
    return mu * x * (1 - x)

mu = 3.9
n_iter = 100000
x = 0.5

lyap_sum = 0.0
burn_in = 1000

for n in range(n_iter):
    x = logistic_map(x, mu)
    if n >= burn_in:
        lyap_sum += np.log(abs(mu * (1 - 2 * x)))  # f'(x) = mu (1-2x)

lyapunov = lyap_sum / (n_iter - burn_in)
print("Exponente de Lyapunov aproximado:", lyapunov)